**This is the baseline model its just 4 simple logistic regression models trained over the dataset from sklearn**

Results from this baseline is that while it gives higher accuracy it is awful at predicting failures as the dataset is extremely biased towards no failure

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [32]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
ai4i_2020_predictive_maintenance_dataset = fetch_ucirepo(id=601) 
  
# data (as pandas dataframes) 
X = ai4i_2020_predictive_maintenance_dataset.data.features 
y = ai4i_2020_predictive_maintenance_dataset.data.targets 
  
# metadata 
print(ai4i_2020_predictive_maintenance_dataset.metadata) 
  
# variable information 
print(ai4i_2020_predictive_maintenance_dataset.variables) 

{'uci_id': 601, 'name': 'AI4I 2020 Predictive Maintenance Dataset', 'repository_url': 'https://archive.ics.uci.edu/dataset/601/ai4i+2020+predictive+maintenance+dataset', 'data_url': 'https://archive.ics.uci.edu/static/public/601/data.csv', 'abstract': 'The AI4I 2020 Predictive Maintenance Dataset is a synthetic dataset that reflects real predictive maintenance data encountered in industry.', 'area': 'Computer Science', 'tasks': ['Classification', 'Regression', 'Causal-Discovery'], 'characteristics': ['Multivariate', 'Time-Series'], 'num_instances': 10000, 'num_features': 6, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'], 'index_col': ['UID', 'Product ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2020, 'last_updated': 'Wed Feb 14 2024', 'dataset_doi': '10.24432/C5HS5C', 'creators': [], 'intro_paper': {'ID': 386, 'type': 'NATIVE', 'title': 'Explainable Artificial Intelligen

In [18]:
X.head()

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
0,M,298.1,308.6,1551,42.8,0
1,L,298.2,308.7,1408,46.3,3
2,L,298.1,308.5,1498,49.4,5
3,L,298.2,308.6,1433,39.5,7
4,L,298.2,308.7,1408,40.0,9


In [19]:
y.head()

,Machine failure,TWF,HDF,PWF,OSF,RNF
0,0,0,0,0,0,0
1,0,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0


In [25]:
y.nunique()

Machine failure    2
TWF                2
HDF                2
PWF                2
OSF                2
RNF                2
dtype: int64

In [33]:
X['Type'] = X['Type'].map({'M': 0, 'L': 1, 'H': 2})

C:\Users\MSI-Admin\AppData\Local\Temp\ipykernel_13788\963275165.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Type'] = X['Type'].map({'M': 0, 'L': 1, 'H': 2})


In [22]:
X.head()

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
0,0,298.1,308.6,1551,42.8,0
1,1,298.2,308.7,1408,46.3,3
2,1,298.1,308.5,1498,49.4,5
3,1,298.2,308.6,1433,39.5,7
4,1,298.2,308.7,1408,40.0,9


In [34]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train, y_train['Machine failure'])
y_pred = model.predict(X_test)
print(classification_report(y_test['Machine failure'], y_pred))
print(confusion_matrix(y_test['Machine failure'], y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1939
           1       0.64      0.26      0.37        61

    accuracy                           0.97      2000
   macro avg       0.81      0.63      0.68      2000
weighted avg       0.97      0.97      0.97      2000

[[1930    9]
 [  45   16]]


In [35]:
model = LogisticRegression()
model.fit(X_train, y_train['TWF'])
y_pred = model.predict(X_test)
print(classification_report(y_test['TWF'], y_pred))
print(confusion_matrix(y_test['TWF'], y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1989
           1       0.00      0.00      0.00        11

    accuracy                           0.99      2000
   macro avg       0.50      0.50      0.50      2000
weighted avg       0.99      0.99      0.99      2000

[[1989    0]
 [  11    0]]


c:\Users\MSI-Admin\Desktop\PRML Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\MSI-Admin\Desktop\PRML Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\MSI-Admin\Desktop\PRML Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [36]:
model = LogisticRegression()
model.fit(X_train, y_train['HDF'])
y_pred = model.predict(X_test)
print(classification_report(y_test['HDF'], y_pred))
print(confusion_matrix(y_test['HDF'], y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1983
           1       0.83      0.29      0.43        17

    accuracy                           0.99      2000
   macro avg       0.91      0.65      0.72      2000
weighted avg       0.99      0.99      0.99      2000

[[1982    1]
 [  12    5]]


In [ ]:
#PWF	OSF	RNF

In [37]:
model = LogisticRegression()
model.fit(X_train, y_train['PWF'])
y_pred = model.predict(X_test)
print(classification_report(y_test['PWF'], y_pred))
print(confusion_matrix(y_test['PWF'], y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1980
           1       0.94      0.75      0.83        20

    accuracy                           1.00      2000
   macro avg       0.97      0.87      0.92      2000
weighted avg       1.00      1.00      1.00      2000

[[1979    1]
 [   5   15]]


In [38]:
model = LogisticRegression()
model.fit(X_train, y_train['OSF'])
y_pred = model.predict(X_test)
print(classification_report(y_test['OSF'], y_pred))
print(confusion_matrix(y_test['OSF'], y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1982
           1       0.71      0.56      0.62        18

    accuracy                           0.99      2000
   macro avg       0.86      0.78      0.81      2000
weighted avg       0.99      0.99      0.99      2000

[[1978    4]
 [   8   10]]


In [39]:
model = LogisticRegression()
model.fit(X_train, y_train['RNF'])
y_pred = model.predict(X_test)
print(classification_report(y_test['RNF'], y_pred))
print(confusion_matrix(y_test['RNF'], y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1994
           1       0.00      0.00      0.00         6

    accuracy                           1.00      2000
   macro avg       0.50      0.50      0.50      2000
weighted avg       0.99      1.00      1.00      2000

[[1994    0]
 [   6    0]]


c:\Users\MSI-Admin\Desktop\PRML Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\MSI-Admin\Desktop\PRML Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\MSI-Admin\Desktop\PRML Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [ ]:
# GOOD RESULTS CUZ OF IMBALANCED DATASET